CREATE TABLE IF NOT EXISTS user_auth (
  id BIGINT NOT NULL,
  email VARCHAR(255) NOT NULL COMMENT '邮箱',
  status TINYINT NOT NULL DEFAULT 1 COMMENT '状态 0 禁用 1 正常',
  password_hash VARCHAR(255) NOT NULL COMMENT '密码哈希',
  create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (id),
  UNIQUE KEY uk_user_auth_email (email)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS user_profile (
  user_id BIGINT NOT NULL,
  nickname VARCHAR(255) COMMENT '昵称',
  avatar_url VARCHAR(255) COMMENT '头像URL',
  gender TINYINT COMMENT '性别',
  birthday DATE COMMENT '生日',
  bio TEXT COMMENT '个人简介',
  create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (user_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS user_session (
  id BIGINT NOT NULL AUTO_INCREMENT,
  user_id BIGINT NOT NULL COMMENT '用户ID',
  token_hash VARCHAR(255) NOT NULL COMMENT 'token哈希',
  revoked TINYINT NOT NULL DEFAULT 1 COMMENT '是否撤销 0 失效 （退出登录） 1 有效',
  expire_time DATETIME COMMENT '过期时间',
  create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (id),
  UNIQUE KEY uk_user_session_user_id (user_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
